<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %><%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Quartos - AgenHotel</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/hospedes.css?v=4"></head><body>
<header class="topo"><div class="topo-conteudo"><h1>AgenHotel</h1><nav><a href="${pageContext.request.contextPath}/hospedes">Hospedes</a><a href="${pageContext.request.contextPath}/quartos">Quartos</a><a href="${pageContext.request.contextPath}/reservas">Reservas</a><a href="${pageContext.request.contextPath}/logout">Sair</a></nav></div></header>
<main class="conteudo conteudo-largo"><div class="titulo-linha"><div><h2>Mapa de quartos</h2><p class="subtexto">Consulte a situacao atual de cada acomodacao. As estadias sao administradas na pagina Reservas.</p></div><a class="botao botao-secundario" href="${pageContext.request.contextPath}/reservas">Ver agenda de reservas</a></div>
<section class="resumo-quartos" aria-label="Resumo dos quartos">
<div class="resumo-item resumo-livre"><span class="resumo-icone">✓</span><div><strong>${livres}</strong><span>Livres agora</span></div></div>
<div class="resumo-item resumo-reservado"><span class="resumo-icone">⌚</span><div><strong>${reservados}</strong><span>Com reserva futura</span></div></div>
<div class="resumo-item resumo-ocupado"><span class="resumo-icone">●</span><div><strong>${ocupados}</strong><span>Ocupados agora</span></div></div>
</section>
<div class="barra-filtros"><div class="filtro-titulo"><strong>Encontre um quarto</strong><span>Combine os filtros para localizar a acomodacao ideal.</span></div><form class="pesquisa pesquisa-completa" method="get"><input name="busca" value="${busca}" placeholder="Numero do quarto"><select name="tipo" aria-label="Categoria"><option value="">Todas as categorias</option><option value="Standard" ${tipoSelecionado == 'Standard' ? 'selected' : ''}>Standard</option><option value="Luxo" ${tipoSelecionado == 'Luxo' ? 'selected' : ''}>Luxo</option><option value="Suite" ${tipoSelecionado == 'Suite' ? 'selected' : ''}>Suite</option></select><select name="situacao" aria-label="Situacao"><option value="">Todas as situacoes</option><option value="LIVRE" ${situacaoSelecionada == 'LIVRE' ? 'selected' : ''}>Livre</option><option value="RESERVADO" ${situacaoSelecionada == 'RESERVADO' ? 'selected' : ''}>Reservado</option><option value="OCUPADO" ${situacaoSelecionada == 'OCUPADO' ? 'selected' : ''}>Ocupado</option></select><button>Filtrar</button><a href="${pageContext.request.contextPath}/quartos">Limpar</a></form></div>
<div class="grade-quartos"><c:forEach var="q" items="${quartos}"><article class="cartao-quarto">
<div class="cartao-quarto-topo"><div><small>QUARTO</small><h3>${q.numero}</h3></div><span class="status status-${q.situacao}">${q.situacao}</span></div>
<p class="tipo-quarto">Acomodacao ${q.tipo}</p><div class="dados-quarto"><span><b>Capacidade</b> Ate ${q.capacidade} pessoa(s)</span><span><b>Valor</b> <strong><fmt:formatNumber value="${q.precoDiaria}" type="currency" currencySymbol="R$"/></strong> por diaria</span></div>
<a class="botao botao-bloco" href="${pageContext.request.contextPath}/reservas?acao=novo&quartoId=${q.id}">Reservar este quarto</a>
</article></c:forEach></div><c:if test="${empty quartos}"><p>Nenhum quarto encontrado.</p></c:if>
<p class="aviso-info"><strong>Importante:</strong> ocupado agora nao significa indisponivel em todas as datas. O sistema confere o periodo escolhido e impede reservas sobrepostas.</p>
</main></body></html>
