<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nova reserva - AgenHotel</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/hospedes.css?v=6"></head><body>
<header class="topo"><div class="topo-conteudo"><h1>AgenHotel</h1><nav><a href="${pageContext.request.contextPath}/hospedes">Hospedes</a><a href="${pageContext.request.contextPath}/quartos">Quartos</a><a href="${pageContext.request.contextPath}/reservas">Reservas</a><a href="${pageContext.request.contextPath}/logout">Sair</a></nav></div></header>
<main class="conteudo form-reserva"><div class="form-cabecalho"><div><span class="etiqueta">NOVA ESTADIA</span><h2>Nova reserva</h2><p class="subtexto">Preencha as tres etapas abaixo. O sistema verificara automaticamente se o quarto esta disponivel no periodo.</p></div><a class="botao botao-secundario" href="${pageContext.request.contextPath}/reservas">Voltar para agenda</a></div><c:if test="${not empty erro}"><p class="erro">${erro}</p></c:if>
<form class="formulario-reserva" method="post" action="${pageContext.request.contextPath}/reservas">
<section class="etapa-form"><div class="numero-etapa">1</div><div class="conteudo-etapa"><h3>Hospede</h3><p>Selecione a pessoa responsavel pela reserva.</p><div class="campo"><label for="hospedeId">Hospede cadastrado</label><select id="hospedeId" name="hospedeId" required><option value="">Selecione um hospede</option><c:forEach var="h" items="${hospedes}"><option value="${h.id}" ${reserva.hospede.id == h.id ? 'selected' : ''}>${h.nome} - ${h.email}</option></c:forEach></select></div></div></section>
<section class="etapa-form"><div class="numero-etapa">2</div><div class="conteudo-etapa"><h3>Acomodacao</h3><p>Escolha o quarto desejado. A situacao exibida corresponde ao momento atual.</p><div class="campo"><label for="quartoId">Quarto desejado</label><select id="quartoId" name="quartoId" required><option value="">Selecione um quarto</option><c:forEach var="q" items="${quartos}"><option value="${q.id}" ${reserva.quarto.id == q.id ? 'selected' : ''}>Quarto ${q.numero} - ${q.tipo} - ate ${q.capacidade} pessoa(s) - ${q.situacao} agora</option></c:forEach></select><small class="ajuda-campo">Mesmo ocupado agora, o quarto pode estar livre nas datas escolhidas.</small></div></div></section>
<section class="etapa-form"><div class="numero-etapa">3</div><div class="conteudo-etapa"><h3>Periodo da estadia</h3><p>Informe a data e escolha o horario de entrada e saida. Os horarios padrao do hotel ja aparecem selecionados.</p><div class="grade-datas">
<div class="bloco-data"><strong>Entrada</strong><div class="linha-data-hora"><div class="campo"><label for="dataCheckin">Data de check-in</label><input class="campo-calendario" type="date" id="dataCheckin" name="dataCheckin" min="${hoje}" value="${reserva.dataCheckin}" onclick="if(this.showPicker){this.showPicker();}" required></div><div class="campo campo-hora"><label for="horaCheckin">Horario</label><select id="horaCheckin" name="horaCheckin" required><option value="12:00" ${reserva.horaCheckin == '12:00' ? 'selected' : ''}>12:00</option><option value="13:00" ${reserva.horaCheckin == '13:00' ? 'selected' : ''}>13:00</option><option value="14:00" ${reserva.horaCheckin == '14:00' ? 'selected' : ''}>14:00 (padrao)</option><option value="15:00" ${reserva.horaCheckin == '15:00' ? 'selected' : ''}>15:00</option><option value="16:00" ${reserva.horaCheckin == '16:00' ? 'selected' : ''}>16:00</option><option value="17:00" ${reserva.horaCheckin == '17:00' ? 'selected' : ''}>17:00</option><option value="18:00" ${reserva.horaCheckin == '18:00' ? 'selected' : ''}>18:00</option><option value="19:00" ${reserva.horaCheckin == '19:00' ? 'selected' : ''}>19:00</option><option value="20:00" ${reserva.horaCheckin == '20:00' ? 'selected' : ''}>20:00</option></select></div></div></div>
<div class="bloco-data"><strong>Saida</strong><div class="linha-data-hora"><div class="campo"><label for="dataCheckout">Data de check-out</label><input class="campo-calendario" type="date" id="dataCheckout" name="dataCheckout" min="${hoje}" value="${reserva.dataCheckout}" onclick="if(this.showPicker){this.showPicker();}" required></div><div class="campo campo-hora"><label for="horaCheckout">Horario</label><select id="horaCheckout" name="horaCheckout" required><option value="08:00" ${reserva.horaCheckout == '08:00' ? 'selected' : ''}>08:00</option><option value="09:00" ${reserva.horaCheckout == '09:00' ? 'selected' : ''}>09:00</option><option value="10:00" ${reserva.horaCheckout == '10:00' ? 'selected' : ''}>10:00</option><option value="11:00" ${reserva.horaCheckout == '11:00' ? 'selected' : ''}>11:00</option><option value="12:00" ${reserva.horaCheckout == '12:00' ? 'selected' : ''}>12:00 (padrao)</option><option value="13:00" ${reserva.horaCheckout == '13:00' ? 'selected' : ''}>13:00</option><option value="14:00" ${reserva.horaCheckout == '14:00' ? 'selected' : ''}>14:00</option><option value="15:00" ${reserva.horaCheckout == '15:00' ? 'selected' : ''}>15:00</option><option value="16:00" ${reserva.horaCheckout == '16:00' ? 'selected' : ''}>16:00</option></select></div></div></div>
</div><div class="horario-padrao"><span>Check-in padrao: <strong>14:00</strong></span><span>Check-out padrao: <strong>12:00</strong></span></div></div></section>
<div class="acoes-form"><a class="botao botao-secundario" href="${pageContext.request.contextPath}/reservas">Cancelar</a><button type="submit">Confirmar e criar reserva</button></div></form></main></body></html>
