<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %><%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reservas - AgenHotel</title><link rel="stylesheet" href="${pageContext.request.contextPath}/css/hospedes.css?v=6"></head><body>
<header class="topo"><div class="topo-conteudo"><h1>AgenHotel</h1><nav><a href="${pageContext.request.contextPath}/hospedes">Hospedes</a><a href="${pageContext.request.contextPath}/quartos">Quartos</a><a href="${pageContext.request.contextPath}/reservas">Reservas</a><a href="${pageContext.request.contextPath}/logout">Sair</a></nav></div></header>
<main class="conteudo conteudo-largo"><div class="titulo-linha"><div><h2>Agenda de reservas</h2><p class="subtexto">Crie estadias e realize check-in, check-out ou cancelamento. Para consultar os quartos, use o Mapa de quartos.</p></div><div class="acoes-topo"><a class="botao botao-secundario" href="${pageContext.request.contextPath}/quartos">Mapa de quartos</a><a class="botao" href="${pageContext.request.contextPath}/reservas?acao=novo">Nova reserva</a></div></div>
<c:if test="${not empty erro}"><p class="erro">${erro}</p></c:if>
<div class="barra-filtros barra-reservas"><div class="filtro-titulo"><strong>Localizar reserva</strong><span>Combine hospede, situacao e quarto.</span></div><form class="pesquisa pesquisa-completa" method="get"><input name="busca" value="${busca}" placeholder="Nome ou e-mail"><select name="status" aria-label="Situacao da reserva"><option value="">Todas as situacoes</option><option value="RESERVADA" ${statusSelecionado == 'RESERVADA' ? 'selected' : ''}>Reservada</option><option value="CHECK_IN" ${statusSelecionado == 'CHECK_IN' ? 'selected' : ''}>Hospedado</option><option value="CHECK_OUT" ${statusSelecionado == 'CHECK_OUT' ? 'selected' : ''}>Finalizada</option><option value="CANCELADA" ${statusSelecionado == 'CANCELADA' ? 'selected' : ''}>Cancelada</option></select><select name="quartoId" aria-label="Quarto"><option value="">Todos os quartos</option><c:forEach var="q" items="${quartos}"><option value="${q.id}" ${quartoSelecionado == q.id ? 'selected' : ''}>Quarto ${q.numero} - ${q.tipo}</option></c:forEach></select><button>Filtrar</button><a href="${pageContext.request.contextPath}/reservas">Limpar</a></form></div>
<div class="cabecalho-lista"><div><h3>Estadias cadastradas</h3><p>As reservas mais recentes aparecem primeiro.</p></div><span class="contador-lista">${reservas.size()} registro(s)</span></div>
<section class="lista-reservas"><c:forEach var="r" items="${reservas}"><article class="cartao-reserva">
<div class="reserva-identificacao"><div class="avatar-hospede">${r.hospede.nome.substring(0,1)}</div><div class="hospede-dados"><small>HOSPEDE</small><h3>${r.hospede.nome}</h3><span>${r.hospede.email}</span></div><span class="status status-${r.status}">${r.status}</span></div>
<div class="reserva-detalhes"><div><small>QUARTO</small><strong>${r.quarto.numero}</strong><span>${r.quarto.tipo}</span></div><div><small>ENTRADA</small><strong>${r.dataCheckin}</strong><span>Check-in as ${r.horaCheckin}</span></div><div><small>SAIDA</small><strong>${r.dataCheckout}</strong><span>Check-out as ${r.horaCheckout}</span></div></div>
<div class="reserva-acoes"><c:choose>
<c:when test="${r.status == 'RESERVADA'}"><span>Proxima etapa: realizar a entrada do hospede.</span><div><a class="botao botao-sucesso" href="${pageContext.request.contextPath}/reservas?acao=checkin&id=${r.id}">Realizar check-in</a><a class="botao botao-perigo" href="${pageContext.request.contextPath}/reservas?acao=cancelar&id=${r.id}" onclick="return confirm('Cancelar reserva?')">Cancelar</a></div></c:when>
<c:when test="${r.status == 'CHECK_IN'}"><span>Hospede atualmente no hotel.</span><div><a class="botao botao-sucesso" href="${pageContext.request.contextPath}/reservas?acao=checkout&id=${r.id}">Realizar check-out</a></div></c:when>
<c:when test="${r.status == 'CHECK_OUT'}"><span>Estadia finalizada. Nenhuma acao pendente.</span></c:when>
<c:otherwise><span>Reserva cancelada.</span></c:otherwise>
</c:choose></div></article></c:forEach></section><c:if test="${empty reservas}"><div class="estado-vazio"><h3>Nenhuma reserva encontrada</h3><p>Tente limpar a pesquisa ou cadastre uma nova reserva.</p></div></c:if></main></body></html>
